# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("besag_morris", "bym2_centroid", "bym2_covariance", "bym2_integrated", "bym2_morris", "bym2_precision", "centroid", "constant", "iid", "integrated", "mvn_covariance", "mvn_precision")

# load each stan module
Rcpp::loadModule("stan_fit4besag_morris_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bym2_centroid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bym2_covariance_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bym2_integrated_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bym2_morris_mod", what = TRUE)
Rcpp::loadModule("stan_fit4bym2_precision_mod", what = TRUE)
Rcpp::loadModule("stan_fit4centroid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4constant_mod", what = TRUE)
Rcpp::loadModule("stan_fit4iid_mod", what = TRUE)
Rcpp::loadModule("stan_fit4integrated_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mvn_covariance_mod", what = TRUE)
Rcpp::loadModule("stan_fit4mvn_precision_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
