// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_arealutils_TMBExports
#include <TMB.hpp>
#include "GammaNLL.hpp"
#include "NormalNLL.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "GammaNLL") {
    return GammaNLL(this);
  } else if(model == "NormalNLL") {
    return NormalNLL(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
