// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_arealutils_TMBExports
#include <TMB.hpp>
#include "iid.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "iid") {
    return iid(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
